### ISSUE TITLE
get some error about SUBSCRIBE renewal

### ISSUE THREAD

**Issue by magicbrighter** [thibauts/node-upnp-device-client#4]
```

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: SUBSCRIBE renewal error
    at ClientRequest.<anonymous> (upnp-mediarenderer-client/node_modules/upnp-device-client/index.js:234:25)

```

> Got some error at those, but hasn't idea to fix this, need some help ,thanks

``` javascript
 var req = http.request(options, function(res) {
            if (res.statusCode !== 200) {
                console.log(err)
                var err = new Error('SUBSCRIBE renewal error');
                err.statusCode = res.statusCode;
                // XXX: should we clear the subscription and release the server here ?
                //self.emit('error', err);
            }

```

**Comment by thibauts** [comment]
Hi. Please post minimal code to reproduce your issue and use github code formatting. Thanks !

**Comment by magicbrighter** [comment]
Update issue already, Thank you.

**Comment by gp-slick-coder** [comment]
I deal also with this error and do not know how do handle it properly. Maybe someone can help.

My case:
1. subscribe to an event (renewTimeout is 30 minutes)
2. set the PC to sleep
3. wake up the PC after 35 minutes
4. the following error is thrown (statusCode: 412)

My question is, what do I have to do, to have a working event subscription back? How to re-initiate the subscription after I get this error?

`{"level":"warn","message":"[UpnpPlaybackDevice] upnpDevice error { Error: SUBSCRIBE renewal error\n    at ClientRequest.<anonymous> (C:\\Apps\\Styrit Music\\prod-libs\\node-upnp-device-client\\index.js:234:25)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at ClientRequest.emit (events.js:211:7)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)\n    at Socket.socketOnData (_http_client.js:440:20)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12) statusCode: 412 } StatusCode: 412","timestamp":"2018-03-28T06:48:29.459Z"}
`

Thanks, George
