### ISSUE TITLE
Error parsing header timeout

### ISSUE THREAD

**Issue by grunjol** [thibauts/node-upnp-device-client#6]
After getting an statusCode 412

```
upnp-mediarenderer-client/node_modules/upnp-device-client/index.js:431
  return Number(header.split('-')[1]);
                      ^
TypeError: Cannot read property 'split' of undefined

```

**Comment by thibauts** [comment]
I pushed a fix and published to npm as a version patch. There were a few `return` statements missing in error handling blocks. Should be fine now. Well, at least it will fail correctly.
